version: 3
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "Dependencies Updates (Bot)"
    reviewers:
      - "ParaskP7"
  - package-ecosystem: "gradle"
    directory: "/app"
    schedule:
      interval: "daily"
    labels:
      - "Dependencies Updates (Bot)"
    reviewers:
      - "ParaskP7"
